services:
  database:
    image: mysql
    restart: always
    ports:
      - '9999:3306'
    networks:
      - sjekk-inn
    expose:
      - '9999'
    volumes:
      - agile-database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=agile-project
      - MYSQL_ROOT_PASSWORD=agileavengers
      - MYSQL_PASSWORD=agileavengers
      - MYSQL_ROOT_HOST=%

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5500:8080'
      - '5501:8081'
    expose:
      - '5500'
      - '5501'
    depends_on:
      database:
         condition: service_healthy

    links:
      - database
    networks:
      - sjekk-inn
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
networks:
  sjekk-inn:
    driver: bridge
volumes:
  agile-database: